name: docker-build
on: push

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: build image
      run: |
        docker build -t seedhodler:ci-build-${{steps.vars.outputs.tag}}
